version: "2"

services:

  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata

  mongoui:
    image: twnel/mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo

  mongodata:
    image: tianon/true
    volumes:
      - /data/db
